# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-11 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Products', models.CharField(choices=[('frog1', 'Frog'), ('puzzle2', 'Puzzle'), ('Face3', 'Face'), ('Carpenter4', 'Carpenter'), ('Vehicles5', 'Vehicles'), ('Shapes6', 'Shapes'), ('Buttons7', 'Buttons')], default='Frog', max_length=6)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
