# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindlebizy', '0002_auto_20170814_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Products',
            field=models.CharField(choices=[('frog1', 'Frog'), ('puzzle2', 'Puzzle'), ('Face3', 'Face'), ('Carpenter4', 'Carpenter'), ('Vehicles5', 'Vehicles'), ('Shapes6', 'Shapes'), ('Buttons7', 'Buttons')], default='Frog', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
